# Generated by Django 3.2.4 on 2021-06-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemophilia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hemophilia',
            name='para_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hemophilia',
            name='title_4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
