# Generated by Django 3.2.4 on 2021-06-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemophilia', '0003_hemophilia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hemophilia',
            name='image_1',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='hemophilia',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='hemophilia',
            name='image_3',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
