# Generated by Django 3.2.4 on 2021-10-22 05:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('hemophilia', '0004_auto_20210623_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hemophilia',
            old_name='title_1',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='hemophilia',
            name='para_1',
        ),
        migrations.RemoveField(
            model_name='hemophilia',
            name='para_2',
        ),
        migrations.RemoveField(
            model_name='hemophilia',
            name='para_3',
        ),
        migrations.RemoveField(
            model_name='hemophilia',
            name='para_4',
        ),
        migrations.RemoveField(
            model_name='hemophilia',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='hemophilia',
            name='title_3',
        ),
        migrations.RemoveField(
            model_name='hemophilia',
            name='title_4',
        ),
        migrations.AddField(
            model_name='hemophilia',
            name='content',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
