# Generated by Django 3.2.4 on 2021-10-22 06:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('hemophilia', '0005_auto_20211022_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hemophilia',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
