# Generated by Django 3.1.6 on 2021-06-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210611_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsnc',
            name='para_2',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='hsnc',
            name='para_3',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
