# Generated by Django 3.1.6 on 2021-06-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210611_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsnc',
            name='para_2',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='hsnc',
            name='para_3',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='hsnc',
            name='title_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hsnc',
            name='title_3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
