# Generated by Django 3.2.4 on 2021-06-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210611_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsnc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hsnc',
            name='para_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsnc',
            name='para_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsnc',
            name='para_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
