# Generated by Django 3.2.4 on 2021-06-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210613_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatMents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=100)),
                ('para_1', models.TextField(blank=True, null=True)),
                ('title_2', models.CharField(blank=True, max_length=100)),
                ('para_2', models.TextField(blank=True, null=True)),
                ('title_3', models.CharField(blank=True, max_length=100)),
                ('para_3', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Treatments',
            },
        ),
    ]
