# Generated by Django 3.2.4 on 2021-06-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsnc',
            name='image_1',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='hsnc',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='hsnc',
            name='image_3',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
