# Generated by Django 3.2.4 on 2021-06-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210623_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatments',
            name='image_1',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='treatments',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='treatments',
            name='image_3',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
