# Generated by Django 3.2.4 on 2021-06-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_contactus_mo_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Real Story', max_length=150)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='realstory')),
            ],
            options={
                'verbose_name_plural': 'Real Stories',
            },
        ),
    ]
