# Generated by Django 3.2.4 on 2021-08-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_realstories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default=' ', max_length=150)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='slider')),
            ],
            options={
                'verbose_name_plural': 'Slider',
            },
        ),
    ]
