# Generated by Django 3.2.4 on 2021-08-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsnc',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
