# Generated by Django 3.2.4 on 2021-10-22 10:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20211022_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatments',
            name='para_1',
        ),
        migrations.RemoveField(
            model_name='treatments',
            name='para_2',
        ),
        migrations.RemoveField(
            model_name='treatments',
            name='para_3',
        ),
        migrations.RemoveField(
            model_name='treatments',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='treatments',
            name='title_3',
        ),
        migrations.AddField(
            model_name='treatments',
            name='content',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
