# Generated by Django 3.2.4 on 2021-10-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20211022_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hsnc',
            name='content',
        ),
        migrations.RemoveField(
            model_name='hsnc',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='hsnc',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='hsnc',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='hsnc',
            name='title_1',
        ),
        migrations.AddField(
            model_name='hsnc',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hsnc',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
    ]
