# Generated by Django 3.2.4 on 2021-10-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20211022_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsnc',
            name='slug',
            field=models.SlugField(),
        ),
    ]
