# Generated by Django 3.2.4 on 2021-10-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_posts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image_1',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
