# Generated by Django 3.2.4 on 2021-10-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vwd', '0003_auto_20211022_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='vwd',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
